### PR TITLE
Make the owner of a dish optional

### PR DESCRIPTION
**Pull request by TheENGR**

### CODE REVIEW

**Review by ChinchillaMan99 — COMMENTED** [review]
What is the behavior when a dish has no user and the menu is requested?

**Comment by TheENGR** [comment]
> What is the behavior when a dish has no user and the menu is requested?

It prints the dish without the "brought by X"
https://github.com/Software-Goofballs/Maitre-d/blob/main/commands/menu.js#L16

image

**Comment by ChinchillaMan99** [comment]
> > What is the behavior when a dish has no user and the menu is requested?
> 
> It prints the dish without the "brought by X" https://github.com/Software-Goofballs/Maitre-d/blob/main/commands/menu.js#L16
> 
> image

Perf

**Review by ChinchillaMan99 — APPROVED** [review]

**Comment by GuardianG13** [comment]
Why not follow with " (Volunteer needed)"/" (Unassigned)" or would you just prefer that to be understood?

**Comment by TheENGR** [comment]
> Why not follow with " (Volunteer needed)"/" (Unassigned)" or would you just prefer that to be understood?

We don't always need to assign a dish, like when we do carryout 

So the default of none is best

**Review by GuardianG13 — APPROVED** [review]
If I had more time and wasn't on my phone, I'd check if the logic could be simplified but looks good otherwise. Great work. Make sure to treat yourself.

**Pull request merged**
